FROM hart/alpine-node:7

RUN apk update && apk add git

WORKDIR /usr/app

RUN npm install --global pm2

COPY ./package*.json ./

COPY ./ ./

RUN npm run build

EXPOSE 3000

USER node

CMD [ "pm2-runtime", "npm", "--", "start" ]
