version: '3'

services:
  app:
      image: docker-nextjs-dev
      build: .
      ports:  
        - 3000:3000
  database:
      image: docker-postgresql
      build: .
      ports:
        - 5432:5432
